"""Slideshow Video Agent - Creates video presentations with AI-generated content.

This package provides tools to create professional video presentations with:
- Static slides generated by Nano Banana Pro
- Voiceover narration generated by Eleven Labs v3
- Animated transitions generated by Kling 2.6 Pro
- Final assembly using FFmpeg

Example usage:
    from scripts import PresentationConfig, Slide, create_slideshow_video

    config = PresentationConfig(
        slides=[
            Slide(
                title="Welcome",
                visual_description="Modern title slide with company branding",
                narration="Welcome to our presentation."
            ),
        ],
        voice="George",
        transition_style="cinematic",
        reference_images=["./Reference Images/logo.png"],
        output_path="./output/presentation.mp4"
    )

    result = create_slideshow_video(config)
"""

from .orchestrator import (
    PresentationConfig,
    Slide,
    create_slideshow_video,
    run_from_json,
    create_simple_presentation,
    estimate_cost,
)

from .slide_generator import (
    generate_slide,
    generate_slide_batch,
    upload_reference_images,
)

from .voiceover import (
    generate_voiceover,
    generate_voiceover_batch,
    get_voice_info,
    VOICES,
    VOICE_DESCRIPTIONS,
)

from .transition_generator import (
    generate_transition,
    generate_transitions_batch,
    list_transition_styles,
    TRANSITION_STYLES,
)

from .video_assembler import (
    assemble_slideshow,
    create_slide_with_audio,
    trim_transition,
    get_duration,
    get_video_info,
)

from .utils import (
    validate_prerequisites,
    print_prerequisites_status,
    list_reference_images,
    get_reference_images_dir,
    check_ffmpeg,
)

__all__ = [
    # Main orchestrator
    "PresentationConfig",
    "Slide",
    "create_slideshow_video",
    "run_from_json",
    "create_simple_presentation",
    "estimate_cost",
    # Slide generation
    "generate_slide",
    "generate_slide_batch",
    "upload_reference_images",
    # Voiceover
    "generate_voiceover",
    "generate_voiceover_batch",
    "get_voice_info",
    "VOICES",
    "VOICE_DESCRIPTIONS",
    # Transitions
    "generate_transition",
    "generate_transitions_batch",
    "list_transition_styles",
    "TRANSITION_STYLES",
    # Video assembly
    "assemble_slideshow",
    "create_slide_with_audio",
    "trim_transition",
    "get_duration",
    "get_video_info",
    # Utilities
    "validate_prerequisites",
    "print_prerequisites_status",
    "list_reference_images",
    "get_reference_images_dir",
    "check_ffmpeg",
]

__version__ = "1.0.0"
